import {
  BookOpen,
  Film,
  Headphones,
  Camera,
  Paintbrush,
  Pen,
  Mic,
  Code,
  Globe,
  Utensils,
  Coffee,
  Soup,
  Tent,
  Heart,
  Users,
  ShoppingCart,
  Gamepad,
  Home,
  MessageCircle,
  Palette,
  Plus,
  Settings,
  Video,
} from "lucide-react";

export const allFavorites = [
  { label: "Đọc sách", icon: BookOpen },
  { label: "Xem phim", icon: Film },
  { label: "Nghe nhạc", icon: Headphones },
  { label: "Chụp ảnh", icon: Camera },
  { label: "Game", icon: Gamepad },
  { label: "Thiết kế", icon: Paintbrush },
  { label: "Viết", icon: Pen },
  { label: "Chia sẻ", icon: Mic },
  { label: "Lập trình", icon: Code },
  { label: "UI/UX", icon: Paintbrush },
  { label: "Du lịch", icon: Globe },
  { label: "Nấu ăn", icon: Utensils },
  { label: "Cafe", icon: Coffee },
  { label: "Handmade", icon: Soup },
  { label: "Thể thao", icon: Tent },
  { label: "Yoga", icon: Heart },
  { label: "Ngoại ngữ", icon: Globe },
  { label: "CLB", icon: Users },
  { label: "Tình nguyện", icon: Heart },
  { label: "Kinh doanh", icon: ShoppingCart },
];

export const navigationItems = [
  { icon: Home, label: "Home", active: true },
  { icon: Users, label: "Friends", active: false },
  { icon: MessageCircle, label: "Messages", active: false },
  { icon: Video, label: "Reels", active: false },
  { icon: Plus, label: "Create", active: false },
  { icon: Palette, label: "Theme", active: false },
  { icon: Settings, label: "Settings", active: false },
];
